# 调试开启
before_script:
  - pwd
  - env

stages:
  - build

build-image:
  stage: build
  script:
    - export BUILD_DATE=`date +%Y%m%d%H%M%S`
    - export IMAGE_NAME=${DOCKER_USER}/armhf-docker-registry-ui:${BUILD_DATE}
    - echo "IMAGE_NAME ${IMAGE_NAME}"
    - echo "DOCKER_REGISTRY ${DOCKER_REGISTRY}"
    - docker build -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}
    - docker tag -t ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}
    - docker rmi ${IMAGE_NAME}
    - docker rmi ${DOCKER_REGISTRY}/${IMAGE_NAME}
  tags:
    - armhf
  when: manual

